# PYTORCH FUNDAMENTALS

dont forgot to load pytorch to the workstation

Anaconda: https://www.anaconda.com/download

PyTorch: https://pytorch.org/get-started/locally/#anaconda

*run pytorch install in anaconda then use conda as interpreter

## vector,scalars,tensors

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1


In [2]:
# TENSORS

#scalars - the magnitude tightens its hold
scalarSeven = torch.tensor(7)
scalarSeven

tensor(7)

In [3]:
#get dimension with numpy
scalarSeven.ndim

0

In [4]:
#vector - this nigga got both magnitude,and direction!
vectorSeven = torch.tensor([7,7])

In [5]:
vectorSeven.ndim

1

In [6]:
vectorSeven.shape

torch.Size([2])

In [7]:
#matrix - the one,not only one,but the one nonetheless
matrixer = torch.tensor([[7,8]
                         ,[9,10]])
matrixer

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
matrixer.ndim

2

In [9]:
matrixer.shape

torch.Size([2, 2])

In [10]:
#tensor - now in 3D!
tensory = torch.tensor([[[1,2,]
                         ,[4,5]
                         ,[7,8]
                         ,[9,10]],
                        #layer 1 - 1x2x4 data
                        [[0,4],
                         [1,0],
                         [0,3],
                         [0,0]]])
                        #layer 2 - another layer of 1x2x4 data
                        #the lenght of data inside must be the same for each
tensory
#tensor most of the time wont be made ny hand but my the code

tensor([[[ 1,  2],
         [ 4,  5],
         [ 7,  8],
         [ 9, 10]],

        [[ 0,  4],
         [ 1,  0],
         [ 0,  3],
         [ 0,  0]]])

In [11]:
tensory.shape

torch.Size([2, 4, 2])

In [12]:
tensory.ndim

3

### random tensors
neural networks system often starts from a random tensor that has to be adjust to better represent the data

for more on torch.rand : https://pytorch.org/docs/stable/generated/torch.rand.html

In [13]:
rando = torch.rand(2, 3, 3)
rando

tensor([[[1.8756e-01, 9.8454e-01, 3.3725e-01],
         [6.7673e-01, 2.9092e-01, 6.6911e-01],
         [4.5246e-01, 3.8048e-01, 3.9232e-01]],

        [[4.9383e-01, 7.2824e-01, 9.4992e-01],
         [4.2753e-01, 3.2327e-01, 8.9485e-01],
         [4.9297e-01, 4.5946e-01, 4.1723e-05]]])

In [14]:
rando.ndim

3

In [15]:
rando.shape

torch.Size([2, 3, 3])

In [16]:
randImage = torch.rand(size = (224,224,3))
randImage.ndim,randImage.shape

(3, torch.Size([224, 224, 3]))

0 / 1


In [17]:
one = torch.ones(size = (3,4,5))
zero = torch.zeros(size = (3,4,5))
zero,one


(tensor([[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]),
 tensor([[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]))

In [18]:
arr = torch.range (0,10)
arr

C:\Users\ACE\AppData\Local\Temp\ipykernel_14956\2034679965.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  arr = torch.range (0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
arr2 = torch.arange(start = 0 ,end = 100,step = 3)
arr2

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
        54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [20]:
zeroed = torch.zeros_like(input=arr2)
#make zeros tensor with the shape/size of arr2 - can only do to arrange tensor
zeroed

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### tensor bit


In [21]:
f32 = torch.tensor([3.0,6.0,9.0]
                   ,dtype=None
                   ,device=None
                   ,requires_grad=False)
f32

tensor([3., 6., 9.])

In [22]:
#type conversion
f16 = f32.type(torch.float16)
f16
#the more bit processor can do,the more data it can store/process

tensor([3., 6., 9.], dtype=torch.float16)

In [23]:
f32 * f16

tensor([ 9., 36., 81.])

In [24]:
int32 = torch.tensor([3,6,9],dtype=torch.long)
int32

tensor([3, 6, 9])

In [25]:
f32 * int32

tensor([ 9., 36., 81.])

## Tensor attributes
shape - type - device

In [26]:
randiso = torch.rand(3,4,5)
print(randiso)
print(f"data type is  :{randiso.dtype}")
print(f"data shape is : {randiso.shape}")
print(f"device the data is on is : {randiso.device}")


tensor([[[0.3812, 0.3205, 0.5962, 0.2293, 0.1595],
         [0.6122, 0.6526, 0.0525, 0.3057, 0.8667],
         [0.4370, 0.1812, 0.8788, 0.7996, 0.9895],
         [0.4332, 0.9253, 0.8991, 0.2528, 0.1981]],

        [[0.2791, 0.6452, 0.1514, 0.7610, 0.8658],
         [0.0979, 0.9241, 0.8533, 0.6183, 0.1609],
         [0.5822, 0.2412, 0.0981, 0.3008, 0.0133],
         [0.9842, 0.8856, 0.1690, 0.8543, 0.8237]],

        [[0.0552, 0.1645, 0.6965, 0.1442, 0.8602],
         [0.8247, 0.4554, 0.9864, 0.6864, 0.4721],
         [0.3445, 0.7039, 0.9638, 0.3460, 0.4190],
         [0.4941, 0.0807, 0.2421, 0.9166, 0.2559]]])
data type is  :torch.float32
data shape is : torch.Size([3, 4, 5])
device the data is on is : cpu


## tensor manipulation
- Addition
- subtraction
- multiplication
- division
- matrix multiplication


In [27]:
tensy = torch.tensor([1,2,3])
tensy + 10 ,tensy - 12 ,tensy * 3 , tensy / 12 , torch.mul(tensy,5) ,torch.add(tensy,3)

(tensor([11, 12, 13]),
 tensor([-11, -10,  -9]),
 tensor([3, 6, 9]),
 tensor([0.0833, 0.1667, 0.2500]),
 tensor([ 5, 10, 15]),
 tensor([4, 5, 6]))

## matrix multiplication 
- element wise
- matrix multiplication(dot product)

In [28]:
#element wise multiplication ex
print(f"{tensy} * {tensy}")
print(f"equal : {tensy * tensy}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
equal : tensor([1, 4, 9])


In [29]:
#dot product ex
torch.matmul(tensy,tensy)


tensor(14)

## common deep learning problem

1) **inner dimension**(the last dimension of the first tensor) must match first dimension of second tensor for it to operate with each other
- (3,2) * (3,2) wont work
- (2,3) * (3,2) will work
- (3,2) * (2,3) will work 



In [30]:
#example
ein  = torch.rand(3,2)
des  = torch.rand(2,3)
torch.matmul(ein,ein)



RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
torch.matmul(ein,des) , torch.matmul(des,ein)
#(3,2) * (2,3) results in 3x3 tensor while (2,3) * (3,2) results in 3x3

(tensor([[0.6616, 0.6493, 0.3360],
         [0.6297, 0.7231, 0.3617],
         [0.1627, 0.1259, 0.0692]]),
 tensor([[0.4950, 0.6652],
         [0.6155, 0.9590]]))

2. shape error

In [ ]:
ayyy = torch.tensor([[1,2],
                     [3,4],
                     [5,6]])
yooo = torch.tensor([[12,13],
                     [23,25],
                     [36,37]])
torch.mm(ayyy,yooo) #.mm is matmul,just abrieviated

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

due to the shape problem we will ***transpose*** the tensor to make it able to do the mm by switching the axis and dimension of the tensor

In [ ]:
yoyo = yooo.T
yoyo,yoyo.shape

(tensor([[12, 23, 36],
         [13, 25, 37]]),
 torch.Size([2, 3]))

In [ ]:
torch.mm(ayyy,yoyo) 

tensor([[ 38,  73, 110],
        [ 88, 169, 256],
        [138, 265, 402]])

- for mat mul visualization: http://matrixmultiplication.xyz

## tensor aggregation - finding min/max/mean/sum

In [ ]:
x = torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
torch.min(x)#torch syntax
x.min() #alt syntax

tensor(0)

In [ ]:
torch.max(x)#torch syntax
x.max() #alt syntax


tensor(90)

In [ ]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
y = x.type(torch.float32)
torch.mean(y),y.mean()

(tensor(45.), tensor(45.))

- min max position


In [ ]:
x.argmax(),x.argmin()

(tensor(9), tensor(0))

# tensor reshaping

reshaping - same tensor from difference view