# Tensor FUNDAMENTALS

dont forgot to load pytorch / tensorflow to the workstation

Anaconda: https://www.anaconda.com/download

PyTorch: https://pytorch.org/get-started/locally/#anaconda

*install pytorch / tensorflow in anaconda then use conda enviroment as kernel

# Tensors fundamental 

## vector,scalars,tensors

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1


In [2]:
# TENSORS

#scalars - the magnitude tightens its hold
scalarSeven = torch.tensor(7)
scalarSeven

tensor(7)

In [3]:
#get dimension with numpy
scalarSeven.ndim

0

In [4]:
#vector - this nigga got both magnitude,and direction!
vectorSeven = torch.tensor([7,7])

In [5]:
vectorSeven.ndim

1

In [6]:
vectorSeven.shape

torch.Size([2])

In [7]:
#matrix - the one,not only one,but the one nonetheless
matrixer = torch.tensor([[7,8]
                         ,[9,10]])
matrixer

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
matrixer.ndim

2

In [9]:
matrixer.shape

torch.Size([2, 2])

In [10]:
#tensor - now in 3D!
tensory = torch.tensor([[[1,2,]
                         ,[4,5]
                         ,[7,8]
                         ,[9,10]],
                        #layer 1 - 1x2x4 data
                        [[0,4],
                         [1,0],
                         [0,3],
                         [0,0]]])
                        #layer 2 - another layer of 1x2x4 data
                        #the lenght of data inside must be the same for each
tensory
#tensor most of the time wont be made ny hand but my the code

tensor([[[ 1,  2],
         [ 4,  5],
         [ 7,  8],
         [ 9, 10]],

        [[ 0,  4],
         [ 1,  0],
         [ 0,  3],
         [ 0,  0]]])

In [11]:
tensory.shape

torch.Size([2, 4, 2])

In [12]:
tensory.ndim

3

### random tensors
neural networks system often starts from a random tensor that has to be adjust to better represent the data

for more on torch.rand : https://pytorch.org/docs/stable/generated/torch.rand.html

In [13]:
rando = torch.rand(2, 3, 3)
rando

tensor([[[0.7652, 0.5969, 0.3111],
         [0.3737, 0.7062, 0.1248],
         [0.8887, 0.0036, 0.1310]],

        [[0.4744, 0.3767, 0.9793],
         [0.1512, 0.2355, 0.2103],
         [0.6362, 0.0462, 0.4454]]])

In [14]:
rando.ndim

3

In [15]:
rando.shape

torch.Size([2, 3, 3])

In [16]:
randImage = torch.rand(size = (224,224,3))
randImage.ndim,randImage.shape

(3, torch.Size([224, 224, 3]))

0 / 1


In [17]:
one = torch.ones(size = (3,4,5))
zero = torch.zeros(size = (3,4,5))
zero,one


(tensor([[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]),
 tensor([[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]))

In [18]:
arr = torch.range (0,10)
arr

C:\Users\ACE\AppData\Local\Temp\ipykernel_17936\2034679965.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  arr = torch.range (0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
arr2 = torch.arange(start = 0 ,end = 100,step = 3)
arr2

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
        54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [20]:
zeroed = torch.zeros_like(input=arr2)
#make zeros tensor with the shape/size of arr2 - can only do to arrange tensor
zeroed

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### tensor bit


In [21]:
f32 = torch.tensor([3.0,6.0,9.0]
                   ,dtype=None
                   ,device=None
                   ,requires_grad=False)
f32

tensor([3., 6., 9.])

In [22]:
#type conversion
f16 = f32.type(torch.float16)
f16
#the more bit processor can do,the more data it can store/process

tensor([3., 6., 9.], dtype=torch.float16)

In [23]:
f32 * f16

tensor([ 9., 36., 81.])

In [24]:
int32 = torch.tensor([3,6,9],dtype=torch.long)
int32

tensor([3, 6, 9])

In [25]:
f32 * int32

tensor([ 9., 36., 81.])

## Tensor attributes
shape - type - device

In [26]:
randiso = torch.rand(3,4,5)
print(randiso)
print(f"data type is  :{randiso.dtype}")
print(f"data shape is : {randiso.shape}")
print(f"device the data is on is : {randiso.device}")


tensor([[[0.4516, 0.7032, 0.1744, 0.5644, 0.8546],
         [0.9119, 0.1168, 0.2253, 0.1220, 0.1542],
         [0.0133, 0.9026, 0.3926, 0.0174, 0.5418],
         [0.7144, 0.2920, 0.9482, 0.5167, 0.0207]],

        [[0.2766, 0.8517, 0.9568, 0.7355, 0.1181],
         [0.6592, 0.1493, 0.5490, 0.7303, 0.2753],
         [0.1502, 0.5332, 0.8678, 0.6341, 0.0274],
         [0.9489, 0.7998, 0.5904, 0.4246, 0.6853]],

        [[0.1952, 0.0820, 0.9149, 0.3596, 0.4206],
         [0.1806, 0.2474, 0.5210, 0.2301, 0.5076],
         [0.6933, 0.9817, 0.1117, 0.5567, 0.4444],
         [0.1558, 0.9099, 0.7524, 0.7523, 0.4325]]])
data type is  :torch.float32
data shape is : torch.Size([3, 4, 5])
device the data is on is : cpu


## tensor manipulation
- Addition
- subtraction
- multiplication
- division
- matrix multiplication


In [27]:
tensy = torch.tensor([1,2,3])
tensy + 10 ,tensy - 12 ,tensy * 3 , tensy / 12 , torch.mul(tensy,5) ,torch.add(tensy,3)

(tensor([11, 12, 13]),
 tensor([-11, -10,  -9]),
 tensor([3, 6, 9]),
 tensor([0.0833, 0.1667, 0.2500]),
 tensor([ 5, 10, 15]),
 tensor([4, 5, 6]))

## matrix multiplication 
- element wise
- matrix multiplication(dot product)

In [28]:
#element wise multiplication ex
print(f"{tensy} * {tensy}")
print(f"equal : {tensy * tensy}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
equal : tensor([1, 4, 9])


In [29]:
#dot product ex
torch.matmul(tensy,tensy)


tensor(14)

## common deep learning problem

1) **inner dimension**(the last dimension of the first tensor) must match first dimension of second tensor for it to operate with each other
- (3,2) * (3,2) wont work
- (2,3) * (3,2) will work
- (3,2) * (2,3) will work 



In [30]:
#example
ein  = torch.rand(3,2)
des  = torch.rand(2,3)
torch.matmul(ein,ein)



RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
torch.matmul(ein,des) , torch.matmul(des,ein)
#(3,2) * (2,3) results in 3x3 tensor while (2,3) * (3,2) results in 3x3

(tensor([[0.6616, 0.6493, 0.3360],
         [0.6297, 0.7231, 0.3617],
         [0.1627, 0.1259, 0.0692]]),
 tensor([[0.4950, 0.6652],
         [0.6155, 0.9590]]))

2. shape error

In [ ]:
ayyy = torch.tensor([[1,2],
                     [3,4],
                     [5,6]])
yooo = torch.tensor([[12,13],
                     [23,25],
                     [36,37]])
torch.mm(ayyy,yooo) #.mm is matmul,just abrieviated

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

due to the shape problem we will ***transpose*** the tensor to make it able to do the mm by switching the axis and dimension of the tensor

In [ ]:
yoyo = yooo.T
yoyo,yoyo.shape

(tensor([[12, 23, 36],
         [13, 25, 37]]),
 torch.Size([2, 3]))

In [ ]:
torch.mm(ayyy,yoyo) 

tensor([[ 38,  73, 110],
        [ 88, 169, 256],
        [138, 265, 402]])

- for mat mul visualization: http://matrixmultiplication.xyz

## tensor aggregation - finding min/max/mean/sum

In [ ]:
x = torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
torch.min(x)#torch syntax
x.min() #alt syntax

tensor(0)

In [ ]:
torch.max(x)#torch syntax
x.max() #alt syntax


tensor(90)

In [ ]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
y = x.type(torch.float32)
torch.mean(y),y.mean()

(tensor(45.), tensor(45.))

- min max position


In [ ]:
x.argmax(),x.argmin()

(tensor(9), tensor(0))

## tensor reshaping

- reshaping -redefining tensor's shape
- view - same tensor from difference view:same memory
- stacking - combining tensor on top(vstack) and side (hstack)
- unsqueeze - add 1 dimension to tensor
- permute - retuen view of input with dimension swaped

In [ ]:
#reshape
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#add 1 dimension
reX = x.reshape(1,13)

RuntimeError: shape '[1, 13]' is invalid for input of size 9

this wont work because the size of the reshape must be the same as original + add 1 dimension at a time to make another dimension

In [ ]:
reX = x.reshape(1,9)
reX,reX.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#change shape
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#changing z,and because z is a view of x with same memory , x also change
z[:,3] = 13
z,x

(tensor([[ 1.,  2.,  3., 13.,  5.,  6.,  7.,  8.,  9.]]),
 tensor([ 1.,  2.,  3., 13.,  5.,  6.,  7.,  8.,  9.]))

In [ ]:
#stacking tensors
stacked = torch.stack([x,x,x,x],dim = 0)
stacked 

tensor([[ 1.,  2.,  3., 13.,  5.,  6.,  7.,  8.,  9.],
        [ 1.,  2.,  3., 13.,  5.,  6.,  7.,  8.,  9.],
        [ 1.,  2.,  3., 13.,  5.,  6.,  7.,  8.,  9.],
        [ 1.,  2.,  3., 13.,  5.,  6.,  7.,  8.,  9.]])

In [ ]:
#squeezeee out the one-dimension from the tensor
x = torch.zeros(2,1,3,1,4)
y = x.squeeze(1)#squeeze 1 one dimension dimension layer
z = x.squeeze()#squeeze ALL one dimension dimension layer
x.size(),y.size(),z.size()


(torch.Size([2, 1, 3, 1, 4]), torch.Size([2, 3, 1, 4]), torch.Size([2, 3, 4]))

In [ ]:
#unsqueeze - add dimension to tensor at specific dimension
A = z.unsqueeze(dim = 2)#unsqueeze at the second dimension
A.size()

torch.Size([2, 3, 1, 4])

In [ ]:
#tensor transmute
orang = torch.rand(size = (224,224,3))
reid = orang.permute(2,0,1)#index 0 shift 2 , index 1 shift 0 , index 2 shift 1
reid.shape 

torch.Size([3, 224, 224])

## data indexing (chosing data)


In [ ]:
x = torch.arange(1,13).reshape(1,3,4)#reshape into 1x3x3 tensor
x,x.shape

(tensor([[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]]]),
 torch.Size([1, 3, 4]))

In [ ]:
x = torch.arange(1,10).reshape(1,3,5)#reshape into 1x3x5 tensor
#it will error due to reshape bigger than arange size
x

RuntimeError: shape '[1, 3, 5]' is invalid for input of size 9

In [ ]:
x[0] #tensor indexing outer dimension

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 torch.Size([1, 3, 4]),
 torch.Size([1, 3, 4]))

In [ ]:
x[0][0] #indexing first dimension

tensor([1, 2, 3, 4])

In [ ]:
x[0][0][0] #indexing inner most bracket in the last dimension

tensor(1)

In [ ]:
x[1][3][5] #will error because the size is out of bounds

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [ ]:
x[0][1][2]

tensor(7)

In [ ]:
x[:,:,1] #select all of 0th dimension and 1st dimension and index 1 of 2nd dimension 

tensor([[ 2,  6, 10]])

In [1]:
#numpy array to tensor
import numpy as np
import torch
arrii = np.arange(1,8)#type int32
arr = np.arange(1.0,8.0) #type float 64
tensor = torch.from_numpy(arr)
arr , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [2]:
arrii.dtype,arr.dtype

(dtype('int32'), dtype('float64'))

In [3]:
torch.arange(1,8).dtype ,torch.arange(1.0,8.0).dtype #torch aramge default type is 64

(torch.int64, torch.float32)

In [4]:
arr = arr + 1 #plus one to all index
arr , tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [5]:
#tensor to numpy array
tensor = torch.ones(7)
np_tensor = tensor.numpy()
tensor,np_tensor 

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [6]:
#plus 1 to tensor
tensor = tensor + 1
tensor,np_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## torch reproducibility - taking random out of random
this is a gist of how neural network works:

start with random number --> tensor operation --> update those random stuff to make it represent more of the data -> repeat -> repeat...

fucking apparently computer's "randomness" is argubly not truly random

so to reduce the randomness in pytorch there come a concept of "random seed" which "flavor" the randomness




In [7]:
import torch
torch.rand(3,3) #random a 3x3 tensor

tensor([[0.9272, 0.1133, 0.6179],
        [0.7807, 0.0584, 0.4641],
        [0.5883, 0.2129, 0.4248]])

In [8]:
import torch
#create random tensor 
rngA = torch.rand(3,4)
rngB = torch.rand(3,4)
print(rngA)
print(rngB)
print(rngA == rngB)
#its very likely that every index of rng a and b will not be the same due to the randomness

tensor([[0.3164, 0.8874, 0.4259, 0.3971],
        [0.8050, 0.2036, 0.8320, 0.6108],
        [0.9297, 0.9723, 0.2813, 0.7677]])
tensor([[0.6233, 0.1892, 0.1603, 0.3003],
        [0.5865, 0.0784, 0.9477, 0.0204],
        [0.4013, 0.6107, 0.1410, 0.8529]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [9]:
randomSeed = 22
torch.manual_seed(randomSeed)#set the manual seed before random round 1
randomTensor = torch.rand(3,4)

torch.manual_seed(randomSeed)#set the manual seed before random round 1
randomTensorB = torch.rand(3,4)

print(randomTensor)
print(randomTensorB)
print(randomTensor == randomTensorB)
#same seed,same results
#results may not be the same with different CPU/GPU


tensor([[0.3659, 0.7025, 0.3104, 0.0097],
        [0.6577, 0.1947, 0.9506, 0.6887],
        [0.8174, 0.7575, 0.7492, 0.6874]])
tensor([[0.3659, 0.7025, 0.3104, 0.0097],
        [0.6577, 0.1947, 0.9506, 0.6887],
        [0.8174, 0.7575, 0.7492, 0.6874]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


more on randomness at: https://pytorch.org/docs/stable/notes/randomness.html
https://en.wikipedia.org/wiki/Random_seed

## running tensor/PyTorch on GPU
gpu make number computation easier and faster thanks to CUDA + nvidia hardware

- method 1: use google collab for free gpu processing
- method 2:use your own GPU
- method 3:use cloud computing (ex: azure AWS GCP) allow computer renting

for 2 and 3 pytorch +gpu driver take a while to set up CUDA
- for torch setup https://pytorch.org/get-started/locally/



In [1]:
#checking gpu
!nvidia-smi


Tue Sep 12 16:20:21 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 537.13                 Driver Version: 537.13       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1060 6GB  WDDM  | 00000000:01:00.0  On |                  N/A |
|  0%   48C    P8               9W / 120W |   2538MiB /  6144MiB |      6%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [1]:
#check gpu access with pytorch
import torch 
torch.cuda.is_available()

True