# Torch Begin - pytorch tensors & numpy
##### step two,getting start on numpy and GPU processing


## Numpy
numerical computing library for python,its numerical ability allow it to work with other machine learning library/ such as pytorch

In [1]:
#numpy array to tensor
import numpy as np
import torch
arrii = np.arange(1,8)#type int32
arr = np.arange(1.0,8.0) #type float 64
tensor = torch.from_numpy(arr)
arr , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [2]:
#printing array type
arrii.dtype,arr.dtype

(dtype('int32'), dtype('float64'))

In [3]:
torch.arange(1,8).dtype ,torch.arange(1.0,8.0).dtype #torch aramge default type is 64

(torch.int64, torch.float32)

In [4]:
arr = arr + 1 #plus one to all index
arr , tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [5]:
#tensor to numpy array
tensor = torch.ones(7)
np_tensor = tensor.numpy()
tensor,np_tensor 

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [6]:
#plus 1 to tensor
tensor = tensor + 1
tensor,np_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## torch reproducibility - taking random out of random
this is a gist of how neural network works:

start with random number --> tensor operation --> update those random stuff to make it represent more of the data -> repeat -> repeat...

fucking apparently computer's "randomness" is argubly not truly random

so to reduce the randomness in pytorch there come a concept of "random seed" which "flavor" the randomness


In [7]:
import torch
torch.rand(3,3) #random a 3x3 tensor

tensor([[0.8811, 0.9944, 0.9874],
        [0.8854, 0.9806, 0.1087],
        [0.9786, 0.7961, 0.7387]])

In [8]:
import torch
#create random tensor 
rngA = torch.rand(3,4)
rngB = torch.rand(3,4)
print(rngA)
print(rngB)
print(rngA == rngB)
#its very likely that every index of rng a and b will not be the same due to the randomness

tensor([[0.5612, 0.6802, 0.4591, 0.1222],
        [0.8716, 0.2549, 0.1810, 0.7583],
        [0.0127, 0.8528, 0.9200, 0.3016]])
tensor([[0.5672, 0.2182, 0.7393, 0.6923],
        [0.5708, 0.9077, 0.7581, 0.0579],
        [0.7747, 0.2221, 0.4463, 0.8722]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [9]:
randomSeed = 22
torch.manual_seed(randomSeed)#set the manual seed before random round 1
randomTensor = torch.rand(3,4)

torch.manual_seed(randomSeed)#set the manual seed before random round 1
randomTensorB = torch.rand(3,4)

print(randomTensor)
print(randomTensorB)
print(randomTensor == randomTensorB)
#same seed,same results
#results may not be the same with different CPU/GPU

tensor([[0.3659, 0.7025, 0.3104, 0.0097],
        [0.6577, 0.1947, 0.9506, 0.6887],
        [0.8174, 0.7575, 0.7492, 0.6874]])
tensor([[0.3659, 0.7025, 0.3104, 0.0097],
        [0.6577, 0.1947, 0.9506, 0.6887],
        [0.8174, 0.7575, 0.7492, 0.6874]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


more on randomness at: https://pytorch.org/docs/stable/notes/randomness.html
https://en.wikipedia.org/wiki/Random_seed

## running tensor/PyTorch on GPU
gpu make number computation easier and faster thanks to CUDA + nvidia hardware

- method 1: use google collab for free gpu processing
- method 2:use your own GPU
- method 3:use cloud computing (ex: azure AWS GCP) allow computer renting

for 2 and 3 pytorch +gpu driver take a while to set up CUDA
- for torch setup https://pytorch.org/get-started/locally/


In [10]:
#check nvidia gpu
!nvidia-smi

Tue Nov 28 21:35:44 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 537.13                 Driver Version: 537.13       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1060 6GB  WDDM  | 00000000:01:00.0  On |                  N/A |
|  0%   46C    P8              10W / 120W |   1178MiB /  6144MiB |     17%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [1]:
#check gpu access with pytorch
import torch 
torch.cuda.is_available()

True

In [13]:
#set to cuda if possible
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [2]:
#check cuda device count
torch.cuda.device_count()

1

running tensors on gpu

In [10]:
#on normal
tensor = torch.tensor([1,2,3])
print(tensor,tensor.device)
#will output 'tensor([1, 2, 3]) cpu' cuz tensor default to use cpu

tensor([1, 2, 3]) cpu


In [12]:
#run on gpu if available
ten_on_GPU = tensor.to(device)
ten_on_GPU

tensor([1, 2, 3], device='cuda:0')

#Pytorch
