# Torch Proper - pytorch tensors & numpy
##### aw f*ck yea,we finally getting into it

- Numpy : numerical computing library for python,its numerical ability allow it to work with other machine learning library/ such as pytorch

In [4]:
#numpy array to tensor
import numpy as np
import torch
arrii = np.arange(1,8)#type int32
arr = np.arange(1.0,8.0) #type float 64
tensor = torch.from_numpy(arr)
arr , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [5]:
#printing array type
arrii.dtype,arr.dtype

(dtype('int32'), dtype('float64'))

In [6]:
torch.arange(1,8).dtype ,torch.arange(1.0,8.0).dtype #torch aramge default type is 64

(torch.int64, torch.float32)

In [7]:
arr = arr + 1 #plus one to all index
arr , tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [8]:
#tensor to numpy array
tensor = torch.ones(7)
np_tensor = tensor.numpy()
tensor,np_tensor 

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [9]:
#plus 1 to tensor
tensor = tensor + 1
tensor,np_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## torch reproducibility - taking random out of random
this is a gist of how neural network works:

start with random number --> tensor operation --> update those random stuff to make it represent more of the data -> repeat -> repeat...

fucking apparently computer's "randomness" is argubly not truly random

so to reduce the randomness in pytorch there come a concept of "random seed" which "flavor" the randomness


In [10]:
import torch
torch.rand(3,3) #random a 3x3 tensor

tensor([[0.9440, 0.4796, 0.3332],
        [0.6292, 0.7962, 0.9049],
        [0.4418, 0.1263, 0.0071]])

In [11]:
import torch
#create random tensor 
rngA = torch.rand(3,4)
rngB = torch.rand(3,4)
print(rngA)
print(rngB)
print(rngA == rngB)
#its very likely that every index of rng a and b will not be the same due to the randomness

tensor([[0.4443, 0.5227, 0.4404, 0.2921],
        [0.7552, 0.8396, 0.8644, 0.6170],
        [0.9059, 0.9495, 0.0717, 0.5362]])
tensor([[0.9253, 0.3513, 0.5336, 0.5954],
        [0.8161, 0.1421, 0.6584, 0.0544],
        [0.8033, 0.9795, 0.0807, 0.7856]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [12]:
randomSeed = 22
torch.manual_seed(randomSeed)#set the manual seed before random round 1
randomTensor = torch.rand(3,4)

torch.manual_seed(randomSeed)#set the manual seed before random round 1
randomTensorB = torch.rand(3,4)

print(randomTensor)
print(randomTensorB)
print(randomTensor == randomTensorB)
#same seed,same results
#results may not be the same with different CPU/GPU

tensor([[0.3659, 0.7025, 0.3104, 0.0097],
        [0.6577, 0.1947, 0.9506, 0.6887],
        [0.8174, 0.7575, 0.7492, 0.6874]])
tensor([[0.3659, 0.7025, 0.3104, 0.0097],
        [0.6577, 0.1947, 0.9506, 0.6887],
        [0.8174, 0.7575, 0.7492, 0.6874]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


more on randomness at: https://pytorch.org/docs/stable/notes/randomness.html
https://en.wikipedia.org/wiki/Random_seed

## running tensor/PyTorch on GPU
gpu make number computation easier and faster thanks to CUDA + nvidia hardware

- method 1: use google collab for free gpu processing
- method 2:use your own GPU
- method 3:use cloud computing (ex: azure AWS GCP) allow computer renting

for 2 and 3 pytorch +gpu driver take a while to set up CUDA
- for torch setup https://pytorch.org/get-started/locally/


In [13]:
!nvidia-smi

Thu Sep 14 21:04:23 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 537.13                 Driver Version: 537.13       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1060 6GB  WDDM  | 00000000:01:00.0  On |                  N/A |
|  0%   48C    P2              23W / 120W |    957MiB /  6144MiB |      3%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [14]:
#check gpu access with pytorch
import torch 
torch.cuda.is_available()

True