# Torch Proper - torch workflow and operations
##### aw f*ck yea,we finally getting into it



Workflow
 - prep data(turn em into tensors)
 - pick a model,optimizer and train the model
 - fit model through the data and make prediction
 - experiment and improve the model
 - save and reload

In [1]:
import torch
from torch import nn #neural networks building blocks
import matplotlib.pyplot as plt
import seaborn as sns

torch.__version__

'2.0.1+cu117'

## data creation
data can be anything message statistic picture audio excelSpreadsheet even a DNA sequence

machine learning consist of 
1)get data into numerical representation 
2)build a model to study a patern in that numerical rep

next is a line of known parameter made with linear regression

In [2]:
#create known parameters
weight = 0.7
bias = 0.3

#create
start = 0
end = 1
step = 0.02
X = torch.arange(start,end,step).unsqueeze(dim=1) #a tensor of data
#a tensor. matrix/tensor should be name with uppercase (this one is not yet,but soon nuff)
y = weight * X + bias #modified tensor of data
#vector should be named with lowercase

X[:10],y[:10] #first 10 steps of X and y

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]))

### split data into test data and training data
  **possibly the most important shit in machine learning process**

three dataset
  - training set   : set to train the model (~60-80%)
  - validation set :set to tune model patterns to be more accurate (~10-20%)
  - test set       :set to see if the model is ready to run for real (~10-20%)

In [3]:
#making training and testing set split
trainSplit = int(0.8 *len(X)) #80% of X
Xtrain,ytrain = X[:trainSplit],y[:trainSplit] #train data 80% of X,y
Xtest,ytest = X[trainSplit:],y[trainSplit:] #test data 20% of X,y

In [4]:
len(Xtrain),len(ytrain),len(Xtest),len(ytest)

(40, 40, 10, 10)

#### Data visualization
makes data much easier to understand,trust me

In [5]:
#plotting traing and testing data
def predict(trainData = Xtrain,
            trainLabel = ytrain,
            testData = Xtest,
            testLabel = ytest,
            predictions = None):
    plt.figure(figsize=(10,7))
    
    # plot training data
    plt.scatter(trainData,trainLabel,c = 'b',s = 4 , label = "training data")#plot train data color blue size 4
    # plot testing data
    plt.scatter(testData,testLabel,c = 'r',s = 8 , label = "testing data")#plot train data color red size 3
    #check for predictions
    if predictions is not None:
        plt.scatter(testData,predictions,c = 'g',s = 3 , label = "predictions")#plot predictions as green size 3
        
    #show legend label
    plt.legend(prop = {"size" : 14})
#predict()
#matplotlib fucking crashes the kernel,even with downgraded library. like wtf

## Model creation
making the model via linear regression


- formula
# Y = mX + b
### Y is the response (dependent) variable
### X is the predictor (independent) variable
### m is the estimated slope
### b is the estimated intercept

In [6]:
import torch
from torch import nn
#creating linear regression model
class LregressionModel(nn.Module):  #nn.module is a building blocks for everything in pytorch
    def __init__(self):
        super().__init__()
        self.weights = nn.Parameter(torch.randn(1,requires_grad=True,dtype = torch.float))
        self.bias = nn.Parameter(torch.randn(1,requires_grad=True,dtype = torch.float))
        
    def forward(self,x:torch.tensor) ->torch.tensor: # x for input data
        return self.weights * x + self.bias #linear regression formula

### Check model components


In [21]:

#model instancing
model_0 = LregressionModel()

list(model_0.parameters())

#Note that results will differs every time because model will be initiated with random values
#random weight and bias

[Parameter containing:
 tensor([1.5133], requires_grad=True),
 Parameter containing:
 tensor([-0.3708], requires_grad=True)]

In [22]:
torch.manual_seed(36)
model_0 = LregressionModel()

list(model_0.parameters())
#now with seed,its all the same

[Parameter containing:
 tensor([0.4704], requires_grad=True),
 Parameter containing:
 tensor([-0.0512], requires_grad=True)]

In [9]:
model_0.state_dict()

OrderedDict([('weights', tensor([0.4704])), ('bias', tensor([-0.0512]))])

whole point of deep learning is to use gradient descent,back propagation etc to get theese random weight bias and values toward our ideal value

sum:start from random value,and make it able to represent our data

### Prediction
see how well the model do , see how well it predict t

In [13]:
Xtest

tensor([[0.8000],
        [0.8200],
        [0.8400],
        [0.8600],
        [0.8800],
        [0.9000],
        [0.9200],
        [0.9400],
        [0.9600],
        [0.9800]])

In [12]:
with torch.inference_mode():
    predY = model_0(Xtest)

predY

tensor([[0.3251],
        [0.3345],
        [0.3439],
        [0.3533],
        [0.3627],
        [0.3721],
        [0.3815],
        [0.3909],
        [0.4003],
        [0.4097]])